# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2024 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: xcop
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: g4s8/xcop-action@v1.3
        with:
          license: LICENSE.txt
          files: |
            **/*.xml
            **/*.xsl
